# Generated by Django 4.2.28 on 2026-02-26 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_customer', models.ImageField(upload_to='passports/customer/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('passport_wife', models.ImageField(upload_to='passports/wife/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('installment_contract', models.ImageField(upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('car_tech_passport', models.ImageField(upload_to='tech_passports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('relative_1_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative 1 Phone')),
                ('relative_2_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative 2 Phone')),
                ('relative_3_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative 3 Phone')),
                ('relative_4_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative 4 Phone')),
                ('relative_5_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative 5 Phone')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
            ],
        ),
    ]
