# Generated by Django 4.2.28 on 2026-02-26 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='car_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/back/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Car Photo (Back)'),
        ),
        migrations.AddField(
            model_name='document',
            name='car_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/front/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Car Photo (Front)'),
        ),
        migrations.AddField(
            model_name='document',
            name='car_photo_left',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/left/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Car Photo (Left)'),
        ),
        migrations.AddField(
            model_name='document',
            name='car_photo_right',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/right/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Car Photo (Right)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='relative_1_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with +996 and contain 8 or 9 digits.', regex='^\\+996\\d{8,9}$')], verbose_name='Relative 1 Phone'),
        ),
        migrations.AlterField(
            model_name='document',
            name='relative_2_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with +996 and contain 8 or 9 digits.', regex='^\\+996\\d{8,9}$')], verbose_name='Relative 2 Phone'),
        ),
        migrations.AlterField(
            model_name='document',
            name='relative_3_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with +996 and contain 8 or 9 digits.', regex='^\\+996\\d{8,9}$')], verbose_name='Relative 3 Phone'),
        ),
        migrations.AlterField(
            model_name='document',
            name='relative_4_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with +996 and contain 8 or 9 digits.', regex='^\\+996\\d{8,9}$')], verbose_name='Relative 4 Phone'),
        ),
        migrations.AlterField(
            model_name='document',
            name='relative_5_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with +996 and contain 8 or 9 digits.', regex='^\\+996\\d{8,9}$')], verbose_name='Relative 5 Phone'),
        ),
    ]
