# Generated by Django 4.2.28 on 2026-02-28 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_car_photo_back_document_car_photo_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='car_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/back/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Car Photo (Back)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='car_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/front/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Car Photo (Front)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='car_photo_left',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/left/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Car Photo (Left)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='car_photo_right',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos/right/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Car Photo (Right)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='car_tech_passport',
            field=models.ImageField(upload_to='tech_passports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='installment_contract',
            field=models.ImageField(upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='passport_customer',
            field=models.ImageField(upload_to='passports/customer/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='passport_wife',
            field=models.ImageField(upload_to='passports/wife/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
